#ifndef __JIELI_NET_H
#define __JIELI_NET_H

enum {
	JIELI_NET_ERROR_OK = 0, 
	JIELI_NET_ERROR_ONLINE, 

	OAUTH_ERROR_USER, 
	OAUTH_ERROR_MALLOC, 
	OAUTH_ERROR_SOCK_CONNECT, 
	OAUTH_ERROR_SOCK_WRITE, 
	OAUTH_ERROR_SOCK_READ, 
	OAUTH_ERROR_BIND, 
	OAUTH_ERROR_TOKEN, 
	OAUTH_ERROR_GET_WAN_IP, 
	OAUTH_ERROR_SEND, 
	OAUTH_ERROR_FILE, 
	OAUTH_ERROR_JSON, 
	OAUTH_ERROR_VOICE_INFO, 

	JIELI_MQTT_ERR_MALLOC,
	JIELI_MQTT_ERR_PTR,
	JIELI_MQTT_ERR_STU,
	JIELI_MQTT_ERR_CLOSE,
	JIELI_MQTT_ERR_SEND,
	JIELI_MQTT_ERR_USER,
	JIELI_MQTT_ERR_JSON,
};

char jieliapp_net_online(void);
char jieliapp_net_ready(void);

int jieli_net_open(void);
void jieli_net_close(void);

#endif /*__JIELI_NET_H*/

